[package]
name = "lazy_vec"
description = "A lazily initialized (but eagerly allocated) Vec-like datastructure"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Joey Ezechiëls"]
rust-version = "1.86.0"

[dependencies]
itertools = "0.14.0"
log = "0.4.27"
tempus_fugit = "0.11.0"
